"""Generate realistic procurement catalog for zakupki.mos.ru demo."""
import json
import random
from pathlib import Path

random.seed(42)

# === Product templates by category ===

PRODUCTS = [
    # --- Ноутбуки (id 1-15) ---
    {"id": 1, "sku": "STE-0001", "title": "Ноутбук Lenovo ThinkBook 15", "category": "ноутбуки", "description": "Офисный ноутбук для закупок, документооборота и видеоконференций.", "price": 68990.0, "tags": ["ноутбук", "lenovo", "офис", "15 дюймов"], "aliases": ["лэптоп", "ноут", "рабочий ноутбук"], "attributes": {"brand": "Lenovo", "cpu": "Intel Core i5", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 2, "sku": "STE-0002", "title": "Ноутбук ASUS ExpertBook B1", "category": "ноутбуки", "description": "Надежный ноутбук для государственных и корпоративных закупок.", "price": 71990.0, "tags": ["ноутбук", "asus", "офис", "business"], "aliases": ["ноут", "лэптоп", "бизнес ноутбук"], "attributes": {"brand": "ASUS", "cpu": "Intel Core i5", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 3, "sku": "STE-0003", "title": "Ноутбук HP ProBook 450 G10", "category": "ноутбуки", "description": "Производительный ноутбук HP для офисных задач и работы с документами.", "price": 74990.0, "tags": ["ноутбук", "hp", "офис", "probook"], "aliases": ["лэптоп hp", "ноут hp"], "attributes": {"brand": "HP", "cpu": "Intel Core i7", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 4, "sku": "STE-0004", "title": "Ноутбук Dell Latitude 5540", "category": "ноутбуки", "description": "Корпоративный ноутбук Dell с усиленной защитой данных.", "price": 82990.0, "tags": ["ноутбук", "dell", "офис", "latitude"], "aliases": ["лэптоп dell", "ноут dell"], "attributes": {"brand": "Dell", "cpu": "Intel Core i7", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 5, "sku": "STE-0005", "title": "Ноутбук Acer TravelMate P2", "category": "ноутбуки", "description": "Бюджетный офисный ноутбук для массовых закупок.", "price": 52990.0, "tags": ["ноутбук", "acer", "бюджет", "офис"], "aliases": ["ноут acer", "лэптоп acer"], "attributes": {"brand": "Acer", "cpu": "Intel Core i3", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 6, "sku": "STE-0006", "title": "Ноутбук Lenovo IdeaPad 3 15", "category": "ноутбуки", "description": "Универсальный ноутбук для учебных заведений и небольших офисов.", "price": 47990.0, "tags": ["ноутбук", "lenovo", "бюджет", "учебный"], "aliases": ["ноут lenovo", "лэптоп"], "attributes": {"brand": "Lenovo", "cpu": "AMD Ryzen 5", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 7, "sku": "STE-0007", "title": "Ноутбук HP 250 G9", "category": "ноутбуки", "description": "Экономичный ноутбук для типовых офисных задач.", "price": 42990.0, "tags": ["ноутбук", "hp", "бюджет", "250"], "aliases": ["ноут", "лэптоп"], "attributes": {"brand": "HP", "cpu": "Intel Core i3", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 8, "sku": "STE-0008", "title": "Ноутбук ASUS VivoBook 15", "category": "ноутбуки", "description": "Компактный ноутбук для выездных сотрудников.", "price": 55990.0, "tags": ["ноутбук", "asus", "vivobook", "мобильный"], "aliases": ["ноут asus", "лэптоп"], "attributes": {"brand": "ASUS", "cpu": "AMD Ryzen 5", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 9, "sku": "STE-0009", "title": "Ноутбук Lenovo ThinkPad E16", "category": "ноутбуки", "description": "Премиальный корпоративный ноутбук с повышенной надёжностью.", "price": 94990.0, "tags": ["ноутбук", "lenovo", "thinkpad", "премиум"], "aliases": ["лэптоп thinkpad", "ноут thinkpad"], "attributes": {"brand": "Lenovo", "cpu": "Intel Core i7", "ram": "32 GB", "ssd": "1 TB"}},
    {"id": 10, "sku": "STE-0010", "title": "Ноутбук Dell Vostro 3520", "category": "ноутбуки", "description": "Ноутбук Dell для малого бизнеса и государственных учреждений.", "price": 58990.0, "tags": ["ноутбук", "dell", "vostro", "офис"], "aliases": ["ноут dell vostro"], "attributes": {"brand": "Dell", "cpu": "Intel Core i5", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 11, "sku": "STE-0011", "title": "Ноутбук Acer Aspire 5 A515", "category": "ноутбуки", "description": "Мультимедийный ноутбук для презентаций и работы с графикой.", "price": 61990.0, "tags": ["ноутбук", "acer", "aspire", "мультимедиа"], "aliases": ["ноут acer aspire"], "attributes": {"brand": "Acer", "cpu": "AMD Ryzen 7", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 12, "sku": "STE-0012", "title": "Ноутбук MSI Modern 15", "category": "ноутбуки", "description": "Тонкий ноутбук для руководителей и выездных совещаний.", "price": 76990.0, "tags": ["ноутбук", "msi", "тонкий", "лёгкий"], "aliases": ["ноут msi", "ультрабук"], "attributes": {"brand": "MSI", "cpu": "Intel Core i7", "ram": "16 GB", "ssd": "512 GB"}},

    # --- Оргтехника: МФУ и принтеры (id 13-30) ---
    {"id": 13, "sku": "STE-0013", "title": "МФУ лазерное HP LaserJet Pro M428fdn", "category": "оргтехника", "description": "Многофункциональное устройство для печати, сканирования и копирования.", "price": 32990.0, "tags": ["мфу", "принтер", "сканер", "hp", "лазерный"], "aliases": ["копир", "многофункциональное устройство", "лазерный принтер"], "attributes": {"brand": "HP", "type": "laser", "color": "mono", "speed": "38 стр/мин"}},
    {"id": 14, "sku": "STE-0014", "title": "МФУ лазерное Brother DCP-L2540DN", "category": "оргтехника", "description": "Компактное лазерное МФУ для малого офиса.", "price": 21990.0, "tags": ["мфу", "brother", "лазерный", "компактный"], "aliases": ["принтер brother", "копир brother"], "attributes": {"brand": "Brother", "type": "laser", "color": "mono", "speed": "30 стр/мин"}},
    {"id": 15, "sku": "STE-0015", "title": "Принтер лазерный HP LaserJet Pro M404dn", "category": "оргтехника", "description": "Высокоскоростной лазерный принтер для большого объёма печати.", "price": 24990.0, "tags": ["принтер", "hp", "лазерный", "высокоскоростной"], "aliases": ["лазерный принтер", "печатающее устройство"], "attributes": {"brand": "HP", "type": "laser", "color": "mono", "speed": "40 стр/мин"}},
    {"id": 16, "sku": "STE-0016", "title": "МФУ цветное Canon i-SENSYS MF657Cdw", "category": "оргтехника", "description": "Цветное лазерное МФУ для маркетинговых и рекламных материалов.", "price": 38990.0, "tags": ["мфу", "canon", "цветной", "лазерный"], "aliases": ["цветной принтер", "цветное мфу"], "attributes": {"brand": "Canon", "type": "laser", "color": "color", "speed": "21 стр/мин"}},
    {"id": 17, "sku": "STE-0017", "title": "Принтер струйный Epson L3250", "category": "оргтехника", "description": "Экономичный струйный принтер с СНПЧ для фотопечати.", "price": 16990.0, "tags": ["принтер", "epson", "струйный", "снпч", "цветной"], "aliases": ["фотопринтер", "струйник"], "attributes": {"brand": "Epson", "type": "inkjet", "color": "color"}},
    {"id": 18, "sku": "STE-0018", "title": "МФУ лазерное Kyocera ECOSYS M2040dn", "category": "оргтехника", "description": "Надёжное МФУ Kyocera с низкой стоимостью печати.", "price": 29990.0, "tags": ["мфу", "kyocera", "лазерный", "экономичный"], "aliases": ["копир kyocera"], "attributes": {"brand": "Kyocera", "type": "laser", "color": "mono", "speed": "40 стр/мин"}},
    {"id": 19, "sku": "STE-0019", "title": "Сканер планшетный Epson Perfection V39", "category": "оргтехника", "description": "Планшетный сканер для оцифровки документов и фотографий.", "price": 8990.0, "tags": ["сканер", "epson", "планшетный"], "aliases": ["сканирующее устройство", "планшетный сканер"], "attributes": {"brand": "Epson", "type": "flatbed", "resolution": "4800 dpi"}},
    {"id": 20, "sku": "STE-0020", "title": "Принтер лазерный Canon i-SENSYS LBP236dw", "category": "оргтехника", "description": "Беспроводной лазерный принтер Canon для офиса.", "price": 19990.0, "tags": ["принтер", "canon", "лазерный", "wifi"], "aliases": ["лазерный принтер canon"], "attributes": {"brand": "Canon", "type": "laser", "color": "mono"}},
    {"id": 21, "sku": "STE-0021", "title": "МФУ лазерное Xerox B225", "category": "оргтехника", "description": "МФУ Xerox для среднего офиса с автоподатчиком документов.", "price": 22990.0, "tags": ["мфу", "xerox", "лазерный", "автоподатчик"], "aliases": ["копир xerox", "мфу ксерокс"], "attributes": {"brand": "Xerox", "type": "laser", "color": "mono"}},
    {"id": 22, "sku": "STE-0022", "title": "Уничтожитель бумаги Fellowes 8Cd", "category": "оргтехника", "description": "Шредер для уничтожения конфиденциальных документов.", "price": 11990.0, "tags": ["шредер", "уничтожитель", "конфиденциальность"], "aliases": ["шредер", "уничтожитель документов", "измельчитель бумаги"], "attributes": {"brand": "Fellowes", "security_level": "P-4"}},
    {"id": 23, "sku": "STE-0023", "title": "Ламинатор Fellowes Jupiter 2 A3", "category": "оргтехника", "description": "Ламинатор формата A3 для защиты документов и плакатов.", "price": 14990.0, "tags": ["ламинатор", "а3", "fellowes"], "aliases": ["ламинирующее устройство"], "attributes": {"brand": "Fellowes", "format": "A3"}},
    {"id": 24, "sku": "STE-0024", "title": "Картридж HP CF226X оригинальный", "category": "расходные материалы", "description": "Оригинальный тонер-картридж HP для LaserJet Pro.", "price": 8490.0, "tags": ["картридж", "hp", "тонер", "расходник"], "aliases": ["тонер hp", "картридж для принтера"], "attributes": {"brand": "HP", "type": "toner", "yield": "9000 стр"}},
    {"id": 25, "sku": "STE-0025", "title": "Картридж Canon 057H оригинальный", "category": "расходные материалы", "description": "Тонер-картридж повышенной ёмкости для Canon i-SENSYS.", "price": 7990.0, "tags": ["картридж", "canon", "тонер", "расходник"], "aliases": ["тонер canon"], "attributes": {"brand": "Canon", "type": "toner", "yield": "10000 стр"}},
    {"id": 26, "sku": "STE-0026", "title": "Чернила Epson 103 комплект 4 цвета", "category": "расходные материалы", "description": "Комплект оригинальных чернил Epson для СНПЧ.", "price": 3490.0, "tags": ["чернила", "epson", "снпч", "расходник"], "aliases": ["краска для принтера", "чернила epson"], "attributes": {"brand": "Epson", "colors": "4"}},
    {"id": 27, "sku": "STE-0027", "title": "Фотобарабан Brother DR-2335", "category": "расходные материалы", "description": "Блок фотобарабана для МФУ Brother.", "price": 5990.0, "tags": ["фотобарабан", "brother", "расходник"], "aliases": ["барабан brother", "drum"], "attributes": {"brand": "Brother", "yield": "12000 стр"}},

    # --- Мониторы (id 28-42) ---
    {"id": 28, "sku": "STE-0028", "title": "Монитор Samsung 27 дюймов IPS", "category": "мониторы", "description": "Монитор для рабочих мест с IPS-матрицей и тонкими рамками.", "price": 24990.0, "tags": ["монитор", "samsung", "27 дюймов", "ips"], "aliases": ["дисплей", "экран"], "attributes": {"brand": "Samsung", "diagonal": "27", "panel": "IPS", "resolution": "1920x1080"}},
    {"id": 29, "sku": "STE-0029", "title": "Монитор Dell P2422H 24 дюйма IPS", "category": "мониторы", "description": "Профессиональный монитор Dell для офисных задач.", "price": 21990.0, "tags": ["монитор", "dell", "24 дюйма", "ips"], "aliases": ["дисплей dell", "экран dell"], "attributes": {"brand": "Dell", "diagonal": "24", "panel": "IPS", "resolution": "1920x1080"}},
    {"id": 30, "sku": "STE-0030", "title": "Монитор LG 27UL500 4K", "category": "мониторы", "description": "4K UHD монитор LG для работы с графикой и документами.", "price": 32990.0, "tags": ["монитор", "lg", "4k", "27 дюймов", "uhd"], "aliases": ["дисплей 4k", "экран lg"], "attributes": {"brand": "LG", "diagonal": "27", "panel": "IPS", "resolution": "3840x2160"}},
    {"id": 31, "sku": "STE-0031", "title": "Монитор Philips 243V7QDSB 24 дюйма", "category": "мониторы", "description": "Бюджетный монитор Philips для массового оснащения.", "price": 14990.0, "tags": ["монитор", "philips", "24 дюйма", "бюджет"], "aliases": ["дисплей philips", "экран"], "attributes": {"brand": "Philips", "diagonal": "24", "panel": "IPS", "resolution": "1920x1080"}},
    {"id": 32, "sku": "STE-0032", "title": "Монитор BenQ GW2480T 24 дюйма", "category": "мониторы", "description": "Монитор с технологией защиты зрения для длительной работы.", "price": 18990.0, "tags": ["монитор", "benq", "24 дюйма", "защита зрения"], "aliases": ["дисплей benq", "экран benq"], "attributes": {"brand": "BenQ", "diagonal": "24", "panel": "IPS"}},
    {"id": 33, "sku": "STE-0033", "title": "Монитор AOC 22B2HN 22 дюйма", "category": "мониторы", "description": "Компактный монитор для рабочих мест с ограниченным пространством.", "price": 10990.0, "tags": ["монитор", "aoc", "22 дюйма", "компактный"], "aliases": ["дисплей aoc", "экран 22"], "attributes": {"brand": "AOC", "diagonal": "22", "panel": "VA"}},
    {"id": 34, "sku": "STE-0034", "title": "Монитор Samsung 32 дюйма Curved", "category": "мониторы", "description": "Изогнутый монитор для руководителей и аналитиков.", "price": 28990.0, "tags": ["монитор", "samsung", "32 дюйма", "изогнутый"], "aliases": ["curved монитор", "экран samsung 32"], "attributes": {"brand": "Samsung", "diagonal": "32", "panel": "VA", "resolution": "2560x1440"}},

    # --- Компьютеры и системные блоки (id 35-48) ---
    {"id": 35, "sku": "STE-0035", "title": "Системный блок iRu Office 310H5", "category": "компьютеры", "description": "Настольный компьютер для оснащения рабочих мест сотрудников.", "price": 54990.0, "tags": ["системный блок", "компьютер", "пк", "офис", "iru"], "aliases": ["системник", "настольный компьютер", "десктоп"], "attributes": {"brand": "iRu", "cpu": "Intel Core i5", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 36, "sku": "STE-0036", "title": "Системный блок HP ProDesk 400 G9", "category": "компьютеры", "description": "Компактный офисный компьютер HP для работы с документами.", "price": 62990.0, "tags": ["системный блок", "hp", "prodesk", "офис"], "aliases": ["системник hp", "пк hp", "десктоп hp"], "attributes": {"brand": "HP", "cpu": "Intel Core i5", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 37, "sku": "STE-0037", "title": "Системный блок Lenovo ThinkCentre M70s", "category": "компьютеры", "description": "Надёжный корпоративный ПК Lenovo для государственных закупок.", "price": 59990.0, "tags": ["системный блок", "lenovo", "thinkcentre", "офис"], "aliases": ["системник lenovo", "пк lenovo"], "attributes": {"brand": "Lenovo", "cpu": "Intel Core i5", "ram": "16 GB", "ssd": "256 GB"}},
    {"id": 38, "sku": "STE-0038", "title": "Системный блок Dell OptiPlex 3000", "category": "компьютеры", "description": "Экономичный офисный ПК Dell для массовых закупок.", "price": 48990.0, "tags": ["системный блок", "dell", "optiplex", "бюджет"], "aliases": ["системник dell", "пк dell"], "attributes": {"brand": "Dell", "cpu": "Intel Core i3", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 39, "sku": "STE-0039", "title": "Моноблок Lenovo IdeaCentre AIO 3 24", "category": "компьютеры", "description": "Моноблок 24 дюйма для компактных рабочих мест.", "price": 64990.0, "tags": ["моноблок", "lenovo", "24 дюйма", "aio"], "aliases": ["all-in-one", "компьютер-моноблок"], "attributes": {"brand": "Lenovo", "cpu": "AMD Ryzen 5", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 40, "sku": "STE-0040", "title": "Моноблок HP ProOne 240 G9", "category": "компьютеры", "description": "Профессиональный моноблок HP для рабочих станций.", "price": 72990.0, "tags": ["моноблок", "hp", "proone", "офис"], "aliases": ["all-in-one hp"], "attributes": {"brand": "HP", "cpu": "Intel Core i5", "ram": "16 GB", "ssd": "512 GB"}},
    {"id": 41, "sku": "STE-0041", "title": "Мини-ПК Intel NUC 12", "category": "компьютеры", "description": "Ультракомпактный компьютер для ограниченного пространства.", "price": 42990.0, "tags": ["мини-пк", "intel", "nuc", "компактный"], "aliases": ["мини компьютер", "неттоп", "nuc"], "attributes": {"brand": "Intel", "cpu": "Intel Core i5", "ram": "8 GB", "ssd": "256 GB"}},
    {"id": 42, "sku": "STE-0042", "title": "Тонкий клиент HP t640", "category": "компьютеры", "description": "Тонкий клиент для терминального доступа и VDI.", "price": 34990.0, "tags": ["тонкий клиент", "hp", "vdi", "терминал"], "aliases": ["thin client", "терминальная станция"], "attributes": {"brand": "HP", "cpu": "AMD Ryzen", "ram": "8 GB"}},

    # --- Мебель (id 43-60) ---
    {"id": 43, "sku": "STE-0043", "title": "Офисное кресло эргономичное Metta SU-BK-8", "category": "мебель", "description": "Кресло с поддержкой поясницы для длительной работы сотрудников.", "price": 21990.0, "tags": ["кресло", "офис", "эргономика", "мебель"], "aliases": ["офисный стул", "эргономичное кресло", "стул офисный"], "attributes": {"brand": "Metta", "material": "mesh"}},
    {"id": 44, "sku": "STE-0044", "title": "Кресло руководителя Chairman 680", "category": "мебель", "description": "Кожаное кресло для кабинета руководителя.", "price": 34990.0, "tags": ["кресло", "руководитель", "кожа", "премиум"], "aliases": ["директорское кресло", "кресло начальника"], "attributes": {"brand": "Chairman", "material": "кожа"}},
    {"id": 45, "sku": "STE-0045", "title": "Стул офисный Бюрократ CH-330M", "category": "мебель", "description": "Бюджетный стул для массового оснащения офисов.", "price": 5990.0, "tags": ["стул", "офис", "бюджет", "бюрократ"], "aliases": ["офисный стул", "стул для офиса"], "attributes": {"brand": "Бюрократ", "material": "ткань"}},
    {"id": 46, "sku": "STE-0046", "title": "Стол письменный 120x60 см", "category": "мебель", "description": "Офисный стол стандартного размера для рабочего места.", "price": 8990.0, "tags": ["стол", "офис", "письменный", "рабочий"], "aliases": ["рабочий стол", "офисный стол", "письменный стол"], "attributes": {"width": "120 см", "depth": "60 см", "material": "ЛДСП"}},
    {"id": 47, "sku": "STE-0047", "title": "Стол письменный угловой 140x120 см", "category": "мебель", "description": "Угловой офисный стол для расширенного рабочего места.", "price": 14990.0, "tags": ["стол", "угловой", "офис", "большой"], "aliases": ["угловой стол", "компьютерный стол"], "attributes": {"width": "140 см", "material": "ЛДСП"}},
    {"id": 48, "sku": "STE-0048", "title": "Стол компьютерный с тумбой", "category": "мебель", "description": "Компьютерный стол с выдвижными ящиками для документов.", "price": 12490.0, "tags": ["стол", "компьютерный", "тумба", "ящики"], "aliases": ["компьютерный стол", "стол с тумбой"], "attributes": {"material": "ЛДСП"}},
    {"id": 49, "sku": "STE-0049", "title": "Шкаф офисный для документов", "category": "мебель", "description": "Шкаф с замком для хранения документов и папок.", "price": 16990.0, "tags": ["шкаф", "офис", "документы", "хранение"], "aliases": ["шкаф для бумаг", "офисный шкаф", "архивный шкаф"], "attributes": {"material": "ЛДСП", "lock": "да"}},
    {"id": 50, "sku": "STE-0050", "title": "Тумба мобильная офисная 3 ящика", "category": "мебель", "description": "Подкатная тумба на колёсиках для рабочего стола.", "price": 6990.0, "tags": ["тумба", "офис", "мобильная", "ящики"], "aliases": ["подкатная тумба", "тумба на колёсах"], "attributes": {"drawers": "3", "material": "ЛДСП"}},
    {"id": 51, "sku": "STE-0051", "title": "Стеллаж офисный открытый 5 полок", "category": "мебель", "description": "Металлический стеллаж для архива и канцелярии.", "price": 7990.0, "tags": ["стеллаж", "офис", "полки", "металлический"], "aliases": ["полка офисная", "этажерка"], "attributes": {"shelves": "5", "material": "металл"}},
    {"id": 52, "sku": "STE-0052", "title": "Вешалка напольная офисная", "category": "мебель", "description": "Напольная вешалка для верхней одежды в офисе.", "price": 3990.0, "tags": ["вешалка", "офис", "напольная"], "aliases": ["стойка для одежды", "гардероб"], "attributes": {"material": "металл"}},
    {"id": 53, "sku": "STE-0053", "title": "Сейф офисный Aiko SB-210K", "category": "мебель", "description": "Металлический сейф для хранения ценностей и документов.", "price": 12990.0, "tags": ["сейф", "хранение", "безопасность", "металлический"], "aliases": ["металлический шкаф", "огнеупорный сейф"], "attributes": {"brand": "Aiko", "lock": "ключевой"}},
    {"id": 54, "sku": "STE-0054", "title": "Доска магнитно-маркерная 120x90 см", "category": "мебель", "description": "Белая доска для совещаний и презентаций.", "price": 4990.0, "tags": ["доска", "маркерная", "магнитная", "презентация"], "aliases": ["маркерная доска", "whiteboard", "доска для записей"], "attributes": {"size": "120x90 см"}},
    {"id": 55, "sku": "STE-0055", "title": "Перегородка офисная мобильная 160x120", "category": "мебель", "description": "Звукопоглощающая перегородка для зонирования офиса.", "price": 9990.0, "tags": ["перегородка", "офис", "зонирование", "мобильная"], "aliases": ["офисная ширма", "разделитель пространства"], "attributes": {"size": "160x120 см"}},

    # --- Периферия (id 56-75) ---
    {"id": 56, "sku": "STE-0056", "title": "Клавиатура Logitech K120", "category": "периферия", "description": "Проводная клавиатура для офисных рабочих мест.", "price": 1590.0, "tags": ["клавиатура", "logitech", "проводная", "usb"], "aliases": ["keyboard", "клава"], "attributes": {"brand": "Logitech", "connection": "USB"}},
    {"id": 57, "sku": "STE-0057", "title": "Мышь Logitech B100", "category": "периферия", "description": "Компьютерная мышь для повседневной офисной работы.", "price": 890.0, "tags": ["мышь", "мышка", "logitech", "проводная"], "aliases": ["компьютерная мышь", "мышка"], "attributes": {"brand": "Logitech", "connection": "USB"}},
    {"id": 58, "sku": "STE-0058", "title": "Клавиатура и мышь Logitech MK270 беспроводные", "category": "периферия", "description": "Беспроводной комплект клавиатура + мышь.", "price": 3290.0, "tags": ["клавиатура", "мышь", "комплект", "беспроводной", "logitech"], "aliases": ["беспроводной комплект", "набор клавиатура мышь"], "attributes": {"brand": "Logitech", "connection": "wireless"}},
    {"id": 59, "sku": "STE-0059", "title": "Мышь беспроводная Logitech M330", "category": "периферия", "description": "Бесшумная беспроводная мышь для тихих офисов.", "price": 2490.0, "tags": ["мышь", "беспроводная", "бесшумная", "logitech"], "aliases": ["бесшумная мышка", "тихая мышь"], "attributes": {"brand": "Logitech", "connection": "wireless"}},
    {"id": 60, "sku": "STE-0060", "title": "Веб-камера Logitech C270", "category": "периферия", "description": "HD веб-камера для видеоконференций.", "price": 3990.0, "tags": ["веб-камера", "logitech", "hd", "видеоконференция"], "aliases": ["вебка", "камера для зума", "камера для видеозвонков"], "attributes": {"brand": "Logitech", "resolution": "720p"}},
    {"id": 61, "sku": "STE-0061", "title": "Веб-камера Logitech C920 PRO HD", "category": "периферия", "description": "Профессиональная Full HD камера для конференц-связи.", "price": 7990.0, "tags": ["веб-камера", "logitech", "fullhd", "профессиональная"], "aliases": ["камера для конференций", "fullhd камера"], "attributes": {"brand": "Logitech", "resolution": "1080p"}},
    {"id": 62, "sku": "STE-0062", "title": "Гарнитура Jabra Evolve2 30", "category": "периферия", "description": "Профессиональная гарнитура для видеозвонков и телефонии.", "price": 6990.0, "tags": ["гарнитура", "jabra", "наушники", "видеозвонки"], "aliases": ["наушники с микрофоном", "headset"], "attributes": {"brand": "Jabra", "connection": "USB"}},
    {"id": 63, "sku": "STE-0063", "title": "Гарнитура Logitech H390", "category": "периферия", "description": "USB-гарнитура с шумоподавлением для офиса.", "price": 3490.0, "tags": ["гарнитура", "logitech", "usb", "шумоподавление"], "aliases": ["наушники logitech", "headset"], "attributes": {"brand": "Logitech", "connection": "USB"}},
    {"id": 64, "sku": "STE-0064", "title": "USB-хаб Hama 4-port USB 3.0", "category": "периферия", "description": "Компактный USB-разветвитель на 4 порта.", "price": 1490.0, "tags": ["usb-хаб", "разветвитель", "usb 3.0"], "aliases": ["usb хаб", "usb разветвитель", "юсб хаб"], "attributes": {"brand": "Hama", "ports": "4"}},
    {"id": 65, "sku": "STE-0065", "title": "Коврик для мыши Buro BU-CLOTH 230x180", "category": "периферия", "description": "Тканевый коврик для мыши стандартного размера.", "price": 290.0, "tags": ["коврик", "мышь", "buro"], "aliases": ["коврик для мышки", "мышиный коврик", "mousepad"], "attributes": {"brand": "Buro", "size": "230x180 мм"}},
    {"id": 66, "sku": "STE-0066", "title": "Подставка для ноутбука металлическая", "category": "периферия", "description": "Эргономичная подставка для ноутбука для правильной осанки.", "price": 2990.0, "tags": ["подставка", "ноутбук", "эргономика"], "aliases": ["стойка для ноутбука", "подставка под лэптоп"], "attributes": {"material": "алюминий"}},
    {"id": 67, "sku": "STE-0067", "title": "Презентер Logitech R500s", "category": "периферия", "description": "Беспроводной пульт для управления презентациями.", "price": 4490.0, "tags": ["презентер", "logitech", "пульт", "презентация"], "aliases": ["пульт для презентаций", "кликер"], "attributes": {"brand": "Logitech", "connection": "Bluetooth"}},

    # --- Канцелярия (id 68-90) ---
    {"id": 68, "sku": "STE-0068", "title": "Бумага офисная А4 Svetocopy 500 листов", "category": "канцелярия", "description": "Белая бумага формата A4 для ежедневной офисной печати.", "price": 490.0, "tags": ["бумага", "а4", "канцелярия", "печать"], "aliases": ["офисная бумага", "бумага для принтера", "бумага а4"], "attributes": {"brand": "Svetocopy", "format": "A4", "sheets": "500"}},
    {"id": 69, "sku": "STE-0069", "title": "Бумага офисная А4 Ballet Universal 500 листов", "category": "канцелярия", "description": "Универсальная бумага для копирования и печати.", "price": 420.0, "tags": ["бумага", "а4", "ballet", "печать"], "aliases": ["бумага для копира", "офисная бумага"], "attributes": {"brand": "Ballet", "format": "A4", "sheets": "500"}},
    {"id": 70, "sku": "STE-0070", "title": "Бумага А3 Svetocopy 500 листов", "category": "канцелярия", "description": "Бумага большого формата для чертежей и плакатов.", "price": 890.0, "tags": ["бумага", "а3", "большой формат"], "aliases": ["бумага для плоттера", "бумага а3"], "attributes": {"brand": "Svetocopy", "format": "A3", "sheets": "500"}},
    {"id": 71, "sku": "STE-0071", "title": "Ручка шариковая BIC Cristal синяя (50 шт)", "category": "канцелярия", "description": "Набор шариковых ручек для канцелярских нужд офиса.", "price": 990.0, "tags": ["ручка", "шариковая", "bic", "синяя"], "aliases": ["шариковая ручка", "авторучка"], "attributes": {"brand": "BIC", "color": "синий", "qty": "50"}},
    {"id": 72, "sku": "STE-0072", "title": "Набор маркеров для доски 4 цвета", "category": "канцелярия", "description": "Маркеры для белой магнитно-маркерной доски.", "price": 590.0, "tags": ["маркер", "доска", "цветной", "канцелярия"], "aliases": ["маркеры для доски", "фломастеры для доски"], "attributes": {"colors": "4"}},
    {"id": 73, "sku": "STE-0073", "title": "Степлер Brauberg №24/6 на 25 листов", "category": "канцелярия", "description": "Офисный степлер для скрепления документов.", "price": 390.0, "tags": ["степлер", "канцелярия", "офис", "brauberg"], "aliases": ["сшиватель"], "attributes": {"brand": "Brauberg"}},
    {"id": 74, "sku": "STE-0074", "title": "Скобы для степлера №24/6 (1000 шт)", "category": "канцелярия", "description": "Скобы для офисного степлера.", "price": 90.0, "tags": ["скобы", "степлер", "канцелярия", "расходник"], "aliases": ["скрепки для степлера"], "attributes": {"size": "24/6", "qty": "1000"}},
    {"id": 75, "sku": "STE-0075", "title": "Папка-регистратор А4 75 мм", "category": "канцелярия", "description": "Папка с арочным механизмом для хранения документов.", "price": 190.0, "tags": ["папка", "регистратор", "а4", "хранение"], "aliases": ["папка-файл", "скоросшиватель", "регистратор"], "attributes": {"format": "A4", "width": "75 мм"}},
    {"id": 76, "sku": "STE-0076", "title": "Файлы-вкладыши А4 100 шт", "category": "канцелярия", "description": "Прозрачные файлы-вкладыши для папок.", "price": 190.0, "tags": ["файл", "вкладыш", "а4", "прозрачный"], "aliases": ["мультифора", "прозрачный файл"], "attributes": {"format": "A4", "qty": "100"}},
    {"id": 77, "sku": "STE-0077", "title": "Ножницы офисные 210 мм", "category": "канцелярия", "description": "Канцелярские ножницы для офисных нужд.", "price": 290.0, "tags": ["ножницы", "канцелярия", "офис"], "aliases": ["канцелярские ножницы"], "attributes": {"length": "210 мм"}},
    {"id": 78, "sku": "STE-0078", "title": "Калькулятор настольный Citizen SDC-812NR", "category": "канцелярия", "description": "12-разрядный настольный калькулятор для бухгалтерии.", "price": 890.0, "tags": ["калькулятор", "citizen", "бухгалтерия", "настольный"], "aliases": ["бухгалтерский калькулятор"], "attributes": {"brand": "Citizen", "digits": "12"}},
    {"id": 79, "sku": "STE-0079", "title": "Клей-карандаш 36 г (12 шт)", "category": "канцелярия", "description": "Набор клеящих карандашей для офисных работ.", "price": 490.0, "tags": ["клей", "канцелярия", "карандаш"], "aliases": ["клей-стик", "клеящий карандаш"], "attributes": {"qty": "12"}},
    {"id": 80, "sku": "STE-0080", "title": "Скотч прозрачный 48 мм x 66 м (6 шт)", "category": "канцелярия", "description": "Упаковочная клейкая лента.", "price": 590.0, "tags": ["скотч", "клейкая лента", "упаковка"], "aliases": ["клейкая лента", "липкая лента"], "attributes": {"qty": "6"}},
    {"id": 81, "sku": "STE-0081", "title": "Точилка электрическая офисная", "category": "канцелярия", "description": "Электрическая точилка для карандашей.", "price": 1490.0, "tags": ["точилка", "электрическая", "карандаш"], "aliases": ["электроточилка"], "attributes": {}},
    {"id": 82, "sku": "STE-0082", "title": "Корзина для бумаг металлическая", "category": "канцелярия", "description": "Мусорная корзина для офисного рабочего места.", "price": 690.0, "tags": ["корзина", "мусор", "офис"], "aliases": ["урна офисная", "мусорка"], "attributes": {"material": "металл"}},
    {"id": 83, "sku": "STE-0083", "title": "Лоток для бумаг горизонтальный 3 яруса", "category": "канцелярия", "description": "Настольный лоток для сортировки входящих документов.", "price": 490.0, "tags": ["лоток", "бумага", "сортировка", "офис"], "aliases": ["лоток для документов", "органайзер для бумаг"], "attributes": {"levels": "3"}},
    {"id": 84, "sku": "STE-0084", "title": "Блок-куб для записей 90x90x90 мм", "category": "канцелярия", "description": "Куб бумажных стикеров для заметок.", "price": 190.0, "tags": ["стикеры", "заметки", "блок", "офис"], "aliases": ["блок для записей", "куб бумажный", "стикер"], "attributes": {"size": "90x90x90 мм"}},

    # --- Сетевое оборудование (id 85-100) ---
    {"id": 85, "sku": "STE-0085", "title": "Wi-Fi роутер Keenetic Start KN-1112", "category": "сетевое оборудование", "description": "Маршрутизатор для организации доступа в сеть в небольшом офисе.", "price": 4490.0, "tags": ["роутер", "маршрутизатор", "wifi", "сеть", "keenetic"], "aliases": ["wifi роутер", "вайфай роутер"], "attributes": {"brand": "Keenetic", "frequency": "2.4 GHz"}},
    {"id": 86, "sku": "STE-0086", "title": "Wi-Fi роутер Keenetic Viva KN-1912", "category": "сетевое оборудование", "description": "Двухдиапазонный роутер для среднего офиса.", "price": 7990.0, "tags": ["роутер", "keenetic", "wifi", "двухдиапазонный"], "aliases": ["маршрутизатор keenetic viva"], "attributes": {"brand": "Keenetic", "frequency": "2.4/5 GHz"}},
    {"id": 87, "sku": "STE-0087", "title": "Коммутатор D-Link DGS-1008D 8 портов", "category": "сетевое оборудование", "description": "Гигабитный неуправляемый коммутатор на 8 портов.", "price": 2990.0, "tags": ["коммутатор", "switch", "d-link", "сеть", "гигабит"], "aliases": ["свитч", "сетевой коммутатор"], "attributes": {"brand": "D-Link", "ports": "8", "speed": "1 Gbps"}},
    {"id": 88, "sku": "STE-0088", "title": "Коммутатор TP-Link TL-SG1024 24 порта", "category": "сетевое оборудование", "description": "Гигабитный коммутатор для стойки серверной комнаты.", "price": 8990.0, "tags": ["коммутатор", "tp-link", "24 порта", "серверная"], "aliases": ["свитч tp-link", "сетевой коммутатор 24"], "attributes": {"brand": "TP-Link", "ports": "24", "speed": "1 Gbps"}},
    {"id": 89, "sku": "STE-0089", "title": "Точка доступа Wi-Fi Ubiquiti UniFi AP AC Lite", "category": "сетевое оборудование", "description": "Потолочная точка доступа для корпоративной Wi-Fi сети.", "price": 9990.0, "tags": ["точка доступа", "wifi", "ubiquiti", "корпоративный"], "aliases": ["access point", "wi-fi точка"], "attributes": {"brand": "Ubiquiti", "speed": "AC1200"}},
    {"id": 90, "sku": "STE-0090", "title": "Патч-корд UTP Cat.5e 3 м (10 шт)", "category": "сетевое оборудование", "description": "Набор сетевых кабелей для подключения к локальной сети.", "price": 990.0, "tags": ["патч-корд", "кабель", "сеть", "utp", "cat5e"], "aliases": ["сетевой кабель", "интернет-кабель", "lan кабель"], "attributes": {"category": "Cat.5e", "length": "3 м", "qty": "10"}},
    {"id": 91, "sku": "STE-0091", "title": "Патч-панель 24 порта Cat.6", "category": "сетевое оборудование", "description": "Панель коммутации для серверного шкафа.", "price": 4990.0, "tags": ["патч-панель", "серверная", "cat6", "коммутация"], "aliases": ["коммутационная панель"], "attributes": {"ports": "24", "category": "Cat.6"}},
    {"id": 92, "sku": "STE-0092", "title": "ИБП APC Back-UPS 650VA", "category": "сетевое оборудование", "description": "Источник бесперебойного питания для рабочего места.", "price": 7490.0, "tags": ["ибп", "ups", "apc", "бесперебойник"], "aliases": ["бесперебойник", "источник бесперебойного питания", "упс"], "attributes": {"brand": "APC", "power": "650 VA"}},
    {"id": 93, "sku": "STE-0093", "title": "ИБП APC Smart-UPS 1500VA", "category": "сетевое оборудование", "description": "ИБП для защиты серверного оборудования.", "price": 29990.0, "tags": ["ибп", "ups", "apc", "сервер", "мощный"], "aliases": ["серверный ибп", "бесперебойник для сервера"], "attributes": {"brand": "APC", "power": "1500 VA"}},
    {"id": 94, "sku": "STE-0094", "title": "Сетевой фильтр Pilot S 5 розеток 3 м", "category": "сетевое оборудование", "description": "Сетевой фильтр с защитой от скачков напряжения.", "price": 1290.0, "tags": ["сетевой фильтр", "пилот", "розетки", "защита"], "aliases": ["пилот", "удлинитель с защитой", "фильтр питания"], "attributes": {"brand": "Pilot", "sockets": "5", "length": "3 м"}},
    {"id": 95, "sku": "STE-0095", "title": "Удлинитель 5 розеток 5 м", "category": "сетевое оборудование", "description": "Удлинитель для подключения офисной техники.", "price": 690.0, "tags": ["удлинитель", "розетка", "электрика"], "aliases": ["переноска"], "attributes": {"sockets": "5", "length": "5 м"}},

    # --- Серверы и СХД (id 96-105) ---
    {"id": 96, "sku": "STE-0096", "title": "Сервер Dell PowerEdge T150", "category": "серверы", "description": "Башенный сервер для малого бизнеса и филиалов.", "price": 149990.0, "tags": ["сервер", "dell", "tower", "poweredge"], "aliases": ["серверное оборудование", "башенный сервер"], "attributes": {"brand": "Dell", "cpu": "Intel Xeon E-2314", "ram": "16 GB"}},
    {"id": 97, "sku": "STE-0097", "title": "Сервер HPE ProLiant DL360 Gen10", "category": "серверы", "description": "Стоечный сервер для центрального офиса.", "price": 289990.0, "tags": ["сервер", "hp", "стоечный", "proliant"], "aliases": ["стоечный сервер", "rack сервер"], "attributes": {"brand": "HPE", "cpu": "Intel Xeon Silver 4214", "ram": "32 GB"}},
    {"id": 98, "sku": "STE-0098", "title": "NAS Synology DS220+ 2-bay", "category": "серверы", "description": "Сетевое хранилище для резервного копирования офисных данных.", "price": 34990.0, "tags": ["nas", "synology", "хранилище", "бэкап"], "aliases": ["сетевое хранилище", "файловое хранилище", "storage"], "attributes": {"brand": "Synology", "bays": "2"}},
    {"id": 99, "sku": "STE-0099", "title": "SSD накопитель Samsung 870 EVO 1TB", "category": "серверы", "description": "Твердотельный накопитель для апгрейда серверов и ПК.", "price": 8990.0, "tags": ["ssd", "samsung", "накопитель", "1 тб"], "aliases": ["твердотельный диск", "ссд", "жёсткий диск"], "attributes": {"brand": "Samsung", "capacity": "1 TB", "type": "SATA"}},
    {"id": 100, "sku": "STE-0100", "title": "HDD Seagate Barracuda 2TB", "category": "серверы", "description": "Жёсткий диск для архивного хранения данных.", "price": 5490.0, "tags": ["hdd", "seagate", "накопитель", "2 тб"], "aliases": ["жёсткий диск", "хард", "винчестер"], "attributes": {"brand": "Seagate", "capacity": "2 TB", "type": "SATA"}},

    # --- Проекторы и экраны (id 101-110) ---
    {"id": 101, "sku": "STE-0101", "title": "Проектор Epson EB-W06", "category": "проекторы", "description": "Офисный проектор для переговорных и конференц-залов.", "price": 42990.0, "tags": ["проектор", "epson", "офис", "презентация"], "aliases": ["мультимедийный проектор", "проекционное оборудование"], "attributes": {"brand": "Epson", "brightness": "3700 lm", "resolution": "WXGA"}},
    {"id": 102, "sku": "STE-0102", "title": "Проектор BenQ MH560", "category": "проекторы", "description": "Full HD проектор для больших конференц-залов.", "price": 54990.0, "tags": ["проектор", "benq", "fullhd", "конференц-зал"], "aliases": ["hd проектор", "проектор для зала"], "attributes": {"brand": "BenQ", "brightness": "3800 lm", "resolution": "1080p"}},
    {"id": 103, "sku": "STE-0103", "title": "Экран для проектора настенный 200x150 см", "category": "проекторы", "description": "Настенный проекционный экран с возвратным механизмом.", "price": 8990.0, "tags": ["экран", "проектор", "настенный", "презентация"], "aliases": ["проекционный экран", "экран для проектора"], "attributes": {"size": "200x150 см", "type": "рулонный"}},
    {"id": 104, "sku": "STE-0104", "title": "Экран для проектора на штативе 180x180 см", "category": "проекторы", "description": "Мобильный экран на треноге для выездных презентаций.", "price": 6990.0, "tags": ["экран", "проектор", "штатив", "мобильный"], "aliases": ["переносной экран", "экран на треноге"], "attributes": {"size": "180x180 см", "type": "на штативе"}},
    {"id": 105, "sku": "STE-0105", "title": "Интерактивная панель 65 дюймов", "category": "проекторы", "description": "Сенсорная панель для интерактивных совещаний и обучения.", "price": 189990.0, "tags": ["интерактивная панель", "сенсорный", "65 дюймов", "конференция"], "aliases": ["интерактивная доска", "смарт-панель", "touchscreen"], "attributes": {"diagonal": "65", "type": "touch"}},

    # --- Телефония (id 106-115) ---
    {"id": 106, "sku": "STE-0106", "title": "Телефон IP Yealink SIP-T31G", "category": "телефония", "description": "IP-телефон для VoIP-коммуникаций в офисе.", "price": 5990.0, "tags": ["телефон", "ip", "yealink", "sip", "voip"], "aliases": ["ip телефон", "сип телефон", "офисный телефон"], "attributes": {"brand": "Yealink", "lines": "2"}},
    {"id": 107, "sku": "STE-0107", "title": "Телефон IP Grandstream GXP1628", "category": "телефония", "description": "Бюджетный IP-телефон с поддержкой 2 линий.", "price": 4490.0, "tags": ["телефон", "ip", "grandstream", "бюджет"], "aliases": ["sip телефон", "voip телефон"], "attributes": {"brand": "Grandstream", "lines": "2"}},
    {"id": 108, "sku": "STE-0108", "title": "Телефон проводной Panasonic KX-TS2352", "category": "телефония", "description": "Аналоговый проводной телефон для общих зон.", "price": 1990.0, "tags": ["телефон", "panasonic", "проводной", "аналоговый"], "aliases": ["стационарный телефон", "домашний телефон"], "attributes": {"brand": "Panasonic"}},
    {"id": 109, "sku": "STE-0109", "title": "Конференц-телефон Poly Trio 8300", "category": "телефония", "description": "Спикерфон для переговорных комнат.", "price": 39990.0, "tags": ["конференц-телефон", "спикерфон", "poly", "переговорная"], "aliases": ["спикерфон", "громкая связь", "конференц-связь"], "attributes": {"brand": "Poly"}},
    {"id": 110, "sku": "STE-0110", "title": "DECT-телефон Panasonic KX-TGC310", "category": "телефония", "description": "Беспроводной телефон для мобильных сотрудников.", "price": 2990.0, "tags": ["телефон", "dect", "panasonic", "беспроводной"], "aliases": ["радиотелефон", "беспроводной телефон"], "attributes": {"brand": "Panasonic"}},

    # --- Программное обеспечение (id 111-120) ---
    {"id": 111, "sku": "STE-0111", "title": "Лицензия Microsoft Office 2024 Standard", "category": "программное обеспечение", "description": "Лицензия MS Office для рабочих станций госучреждений.", "price": 18990.0, "tags": ["лицензия", "microsoft", "office", "по"], "aliases": ["офис майкрософт", "ms office", "ворд эксель"], "attributes": {"brand": "Microsoft", "type": "perpetual"}},
    {"id": 112, "sku": "STE-0112", "title": "Лицензия Windows 11 Pro", "category": "программное обеспечение", "description": "Операционная система Windows для корпоративных ПК.", "price": 14990.0, "tags": ["лицензия", "windows", "ос", "microsoft"], "aliases": ["виндовс", "windows pro", "операционная система"], "attributes": {"brand": "Microsoft", "version": "11 Pro"}},
    {"id": 113, "sku": "STE-0113", "title": "Антивирус Kaspersky Endpoint Security 1 год", "category": "программное обеспечение", "description": "Корпоративный антивирус для защиты рабочих станций.", "price": 3490.0, "tags": ["антивирус", "kaspersky", "безопасность", "лицензия"], "aliases": ["касперский", "антивирусная защита"], "attributes": {"brand": "Kaspersky", "duration": "1 год"}},
    {"id": 114, "sku": "STE-0114", "title": "МойОфис Стандартный 2024", "category": "программное обеспечение", "description": "Отечественный офисный пакет для импортозамещения.", "price": 4990.0, "tags": ["мойофис", "офисный пакет", "импортозамещение", "лицензия"], "aliases": ["мой офис", "российский офис"], "attributes": {"brand": "МойОфис", "type": "perpetual"}},
    {"id": 115, "sku": "STE-0115", "title": "Astra Linux Special Edition", "category": "программное обеспечение", "description": "Российская сертифицированная ОС для государственных учреждений.", "price": 9990.0, "tags": ["astra linux", "ос", "импортозамещение", "сертифицированная"], "aliases": ["астра линукс", "российская ос"], "attributes": {"brand": "Astra Linux", "certification": "ФСТЭК"}},
    {"id": 116, "sku": "STE-0116", "title": "1С:Бухгалтерия ПРОФ лицензия", "category": "программное обеспечение", "description": "Программа бухгалтерского учёта для государственных учреждений.", "price": 13800.0, "tags": ["1с", "бухгалтерия", "учёт", "лицензия"], "aliases": ["одинэска", "один-эс", "бухгалтерская программа"], "attributes": {"brand": "1C", "type": "perpetual"}},

    # --- Освещение (id 117-125) ---
    {"id": 117, "sku": "STE-0117", "title": "Светильник офисный LED 595x595 мм 40W", "category": "освещение", "description": "Встраиваемый LED-светильник для потолка Армстронг.", "price": 2490.0, "tags": ["светильник", "led", "офис", "потолочный"], "aliases": ["лампа офисная", "потолочный свет", "панель led"], "attributes": {"power": "40W", "size": "595x595 мм"}},
    {"id": 118, "sku": "STE-0118", "title": "Лампа настольная офисная LED", "category": "освещение", "description": "Настольная лампа с регулировкой яркости для рабочего стола.", "price": 2990.0, "tags": ["лампа", "настольная", "led", "офис"], "aliases": ["настольный светильник", "лампа для стола"], "attributes": {"power": "10W", "dimming": "да"}},
    {"id": 119, "sku": "STE-0119", "title": "Лампа LED A60 E27 12W (10 шт)", "category": "освещение", "description": "Набор светодиодных ламп для офисного освещения.", "price": 990.0, "tags": ["лампа", "led", "e27", "лампочка"], "aliases": ["светодиодная лампа", "лампочка"], "attributes": {"power": "12W", "socket": "E27", "qty": "10"}},
    {"id": 120, "sku": "STE-0120", "title": "Светильник аварийного освещения", "category": "освещение", "description": "Аварийный светильник с аккумулятором для эвакуационного освещения.", "price": 1990.0, "tags": ["аварийный", "светильник", "эвакуация", "безопасность"], "aliases": ["аварийное освещение", "эвакуационный свет"], "attributes": {"battery": "да"}},

    # --- Хозтовары (id 121-140) ---
    {"id": 121, "sku": "STE-0121", "title": "Диспенсер для бумажных полотенец", "category": "хозтовары", "description": "Настенный диспенсер для бумажных полотенец в санузлах.", "price": 2490.0, "tags": ["диспенсер", "полотенца", "санузел", "хозтовары"], "aliases": ["держатель для полотенец"], "attributes": {}},
    {"id": 122, "sku": "STE-0122", "title": "Бумажные полотенца V-сложения (20 пачек)", "category": "хозтовары", "description": "Листовые бумажные полотенца для офисных санузлов.", "price": 1490.0, "tags": ["полотенца", "бумажные", "хозтовары", "санузел"], "aliases": ["бумажные салфетки", "полотенца для рук"], "attributes": {"qty": "20 пачек"}},
    {"id": 123, "sku": "STE-0123", "title": "Туалетная бумага Tork (12 рулонов)", "category": "хозтовары", "description": "Туалетная бумага для офисных санузлов.", "price": 890.0, "tags": ["туалетная бумага", "tork", "хозтовары"], "aliases": ["т/бумага"], "attributes": {"brand": "Tork", "qty": "12"}},
    {"id": 124, "sku": "STE-0124", "title": "Мыло жидкое с дозатором 500 мл (12 шт)", "category": "хозтовары", "description": "Жидкое мыло для офисных санузлов.", "price": 1490.0, "tags": ["мыло", "жидкое", "дозатор", "хозтовары"], "aliases": ["жидкое мыло"], "attributes": {"volume": "500 мл", "qty": "12"}},
    {"id": 125, "sku": "STE-0125", "title": "Средство для мытья полов 5 л", "category": "хозтовары", "description": "Универсальное моющее средство для уборки офиса.", "price": 590.0, "tags": ["моющее средство", "уборка", "полы", "хозтовары"], "aliases": ["средство для уборки", "моющее для полов"], "attributes": {"volume": "5 л"}},
    {"id": 126, "sku": "STE-0126", "title": "Кулер для воды напольный", "category": "хозтовары", "description": "Напольный кулер с нагревом и охлаждением для офиса.", "price": 8990.0, "tags": ["кулер", "вода", "офис", "напольный"], "aliases": ["водный кулер", "диспенсер для воды"], "attributes": {"type": "напольный", "cooling": "да"}},
    {"id": 127, "sku": "STE-0127", "title": "Вода питьевая 19 л бутыль", "category": "хозтовары", "description": "Бутыль питьевой воды для офисного кулера.", "price": 290.0, "tags": ["вода", "питьевая", "бутыль", "19л"], "aliases": ["бутыль для кулера", "питьевая вода"], "attributes": {"volume": "19 л"}},
    {"id": 128, "sku": "STE-0128", "title": "Кофемашина автоматическая DeLonghi", "category": "хозтовары", "description": "Автоматическая кофемашина для кофе-зоны офиса.", "price": 42990.0, "tags": ["кофемашина", "delonghi", "кофе", "офис"], "aliases": ["кофеварка", "кофе-машина"], "attributes": {"brand": "DeLonghi", "type": "автомат"}},
    {"id": 129, "sku": "STE-0129", "title": "Микроволновая печь Samsung 23 л", "category": "хозтовары", "description": "Микроволновка для обеденной зоны офиса.", "price": 6990.0, "tags": ["микроволновка", "samsung", "кухня", "офис"], "aliases": ["свч", "свч-печь", "микроволновая печь"], "attributes": {"brand": "Samsung", "volume": "23 л"}},
    {"id": 130, "sku": "STE-0130", "title": "Чайник электрический 1.7 л", "category": "хозтовары", "description": "Электрочайник для офисной кухни.", "price": 1990.0, "tags": ["чайник", "электрический", "кухня"], "aliases": ["электрочайник"], "attributes": {"volume": "1.7 л"}},

    # --- Средства безопасности (id 131-140) ---
    {"id": 131, "sku": "STE-0131", "title": "Огнетушитель порошковый ОП-4", "category": "безопасность", "description": "Порошковый огнетушитель для офисных помещений.", "price": 1290.0, "tags": ["огнетушитель", "порошковый", "безопасность", "пожарный"], "aliases": ["пожарный огнетушитель"], "attributes": {"type": "порошковый", "capacity": "4 кг"}},
    {"id": 132, "sku": "STE-0132", "title": "Аптечка первой помощи офисная", "category": "безопасность", "description": "Укомплектованная аптечка по требованиям охраны труда.", "price": 990.0, "tags": ["аптечка", "первая помощь", "охрана труда"], "aliases": ["медицинская аптечка", "аптечка для офиса"], "attributes": {}},
    {"id": 133, "sku": "STE-0133", "title": "Камера видеонаблюдения Hikvision 2 Мп", "category": "безопасность", "description": "IP-камера для видеонаблюдения в офисных помещениях.", "price": 5990.0, "tags": ["камера", "видеонаблюдение", "hikvision", "ip"], "aliases": ["камера наблюдения", "видеокамера", "ip камера"], "attributes": {"brand": "Hikvision", "resolution": "2 Мп"}},
    {"id": 134, "sku": "STE-0134", "title": "Видеорегистратор Hikvision 8-канальный", "category": "безопасность", "description": "Сетевой видеорегистратор для записи видеопотоков.", "price": 14990.0, "tags": ["видеорегистратор", "hikvision", "nvr", "8 каналов"], "aliases": ["nvr", "регистратор видео"], "attributes": {"brand": "Hikvision", "channels": "8"}},
    {"id": 135, "sku": "STE-0135", "title": "СКУД контроллер Болид С2000-2", "category": "безопасность", "description": "Контроллер системы контроля доступа для офиса.", "price": 8990.0, "tags": ["скуд", "контроллер", "доступ", "безопасность"], "aliases": ["система контроля доступа", "контроллер доступа"], "attributes": {"brand": "Болид"}},
    {"id": 136, "sku": "STE-0136", "title": "Считыватель карт СКУД Proximity", "category": "безопасность", "description": "Считыватель бесконтактных карт для системы доступа.", "price": 2990.0, "tags": ["считыватель", "скуд", "карта", "proximity"], "aliases": ["кардридер скуд", "считыватель пропусков"], "attributes": {"type": "Proximity"}},

    # --- Спецодежда и СИЗ (id 137-145) ---
    {"id": 137, "sku": "STE-0137", "title": "Халат рабочий (10 шт)", "category": "спецодежда", "description": "Рабочие халаты для технического персонала.", "price": 7990.0, "tags": ["халат", "спецодежда", "рабочий"], "aliases": ["рабочий халат"], "attributes": {"qty": "10"}},
    {"id": 138, "sku": "STE-0138", "title": "Перчатки рабочие нитриловые (100 шт)", "category": "спецодежда", "description": "Одноразовые нитриловые перчатки для хозяйственных работ.", "price": 690.0, "tags": ["перчатки", "нитриловые", "одноразовые"], "aliases": ["нитриловые перчатки", "перчатки для уборки"], "attributes": {"qty": "100"}},
    {"id": 139, "sku": "STE-0139", "title": "Жилет сигнальный оранжевый (10 шт)", "category": "спецодежда", "description": "Сигнальный жилет для работников на открытых площадках.", "price": 1990.0, "tags": ["жилет", "сигнальный", "безопасность"], "aliases": ["светоотражающий жилет"], "attributes": {"qty": "10"}},

    # --- Электрика (id 140-150) ---
    {"id": 140, "sku": "STE-0140", "title": "Кабель-канал 40x20 мм 2 м (10 шт)", "category": "электрика", "description": "Пластиковый кабель-канал для прокладки проводов.", "price": 1490.0, "tags": ["кабель-канал", "электрика", "монтаж", "провод"], "aliases": ["короб для кабеля", "кабельный канал"], "attributes": {"size": "40x20 мм", "qty": "10"}},
    {"id": 141, "sku": "STE-0141", "title": "Розетка двойная встраиваемая", "category": "электрика", "description": "Электрическая розетка для офисного ремонта.", "price": 490.0, "tags": ["розетка", "электрика", "встраиваемая"], "aliases": ["электрическая розетка", "розетка 220"], "attributes": {}},
    {"id": 142, "sku": "STE-0142", "title": "Выключатель одноклавишный", "category": "электрика", "description": "Выключатель освещения для офисных помещений.", "price": 290.0, "tags": ["выключатель", "электрика", "освещение"], "aliases": ["свет выключатель"], "attributes": {}},

    # --- Табл. и информ. стенды (id 143-150) ---
    {"id": 143, "sku": "STE-0143", "title": "Информационный стенд А4 6 карманов", "category": "канцелярия", "description": "Настенный информационный стенд для объявлений.", "price": 1990.0, "tags": ["стенд", "информационный", "объявления", "караман"], "aliases": ["доска объявлений", "информстенд"], "attributes": {"pockets": "6", "format": "A4"}},
    {"id": 144, "sku": "STE-0144", "title": "Табличка на дверь офисная", "category": "канцелярия", "description": "Табличка с названием кабинета для дверей.", "price": 490.0, "tags": ["табличка", "дверь", "офис", "навигация"], "aliases": ["дверная табличка", "вывеска на дверь"], "attributes": {}},
    {"id": 145, "sku": "STE-0145", "title": "Флипчарт передвижной 70x100 см", "category": "канцелярия", "description": "Мольберт для презентаций и мозговых штурмов.", "price": 4990.0, "tags": ["флипчарт", "мольберт", "презентация"], "aliases": ["презентационная доска", "мольберт для совещаний"], "attributes": {"size": "70x100 см"}},
    {"id": 146, "sku": "STE-0146", "title": "Блокнот для флипчарта 20 листов", "category": "канцелярия", "description": "Сменные листы для флипчарта.", "price": 490.0, "tags": ["блокнот", "флипчарт", "бумага"], "aliases": ["бумага для флипчарта"], "attributes": {"sheets": "20"}},

    # --- Дополнительная переферия и аксессуары (id 147-155) ---
    {"id": 147, "sku": "STE-0147", "title": "Флешка USB 3.0 32 GB (10 шт)", "category": "периферия", "description": "Набор USB-накопителей для передачи файлов.", "price": 2990.0, "tags": ["флешка", "usb", "накопитель", "32 гб"], "aliases": ["usb накопитель", "флеш-диск", "юсб флешка"], "attributes": {"capacity": "32 GB", "qty": "10"}},
    {"id": 148, "sku": "STE-0148", "title": "Внешний SSD Samsung T7 1TB", "category": "периферия", "description": "Портативный внешний SSD для резервного копирования.", "price": 9990.0, "tags": ["внешний ssd", "samsung", "портативный", "1 тб"], "aliases": ["внешний диск", "портативный накопитель"], "attributes": {"brand": "Samsung", "capacity": "1 TB"}},
    {"id": 149, "sku": "STE-0149", "title": "Адаптер USB-C / HDMI / USB-A", "category": "периферия", "description": "Универсальный адаптер-хаб для ноутбука.", "price": 2490.0, "tags": ["адаптер", "usb-c", "hdmi", "хаб"], "aliases": ["переходник", "dock", "хаб для ноутбука"], "attributes": {}},
    {"id": 150, "sku": "STE-0150", "title": "Кабель HDMI 2.0 3 м (5 шт)", "category": "периферия", "description": "Набор HDMI-кабелей для подключения мониторов и проекторов.", "price": 1490.0, "tags": ["кабель", "hdmi", "монитор", "проектор"], "aliases": ["hdmi шнур"], "attributes": {"version": "2.0", "length": "3 м", "qty": "5"}},

    # --- Кондиционирование и климат (id 151-155) ---
    {"id": 151, "sku": "STE-0151", "title": "Кондиционер сплит-система 12 BTU", "category": "климат", "description": "Сплит-система для офисных помещений до 35 м².", "price": 34990.0, "tags": ["кондиционер", "сплит-система", "климат", "охлаждение"], "aliases": ["сплит-система", "кондёр"], "attributes": {"power": "12000 BTU"}},
    {"id": 152, "sku": "STE-0152", "title": "Обогреватель масляный 2 кВт", "category": "климат", "description": "Масляный радиатор для дополнительного обогрева офиса.", "price": 3990.0, "tags": ["обогреватель", "масляный", "радиатор", "тепло"], "aliases": ["масляный обогреватель", "радиатор"], "attributes": {"power": "2 кВт"}},
    {"id": 153, "sku": "STE-0153", "title": "Увлажнитель воздуха ультразвуковой", "category": "климат", "description": "Увлажнитель для поддержания комфортного климата.", "price": 4990.0, "tags": ["увлажнитель", "воздух", "климат", "офис"], "aliases": ["увлажнитель воздуха"], "attributes": {"type": "ультразвуковой"}},
    {"id": 154, "sku": "STE-0154", "title": "Вентилятор напольный 40 см", "category": "климат", "description": "Напольный вентилятор для жаркого времени года.", "price": 2490.0, "tags": ["вентилятор", "напольный", "климат"], "aliases": ["напольный вентилятор"], "attributes": {"diameter": "40 см"}},
    {"id": 155, "sku": "STE-0155", "title": "Очиститель воздуха HEPA", "category": "климат", "description": "Очиститель воздуха с HEPA-фильтром для аллергиков.", "price": 12990.0, "tags": ["очиститель", "воздух", "hepa", "фильтр"], "aliases": ["воздухоочиститель", "фильтр воздуха"], "attributes": {"filter": "HEPA"}},

    # --- Планшеты (id 156-160) ---
    {"id": 156, "sku": "STE-0156", "title": "Планшет Samsung Galaxy Tab A8 10.5", "category": "планшеты", "description": "Планшет для выездных сотрудников и мобильных рабочих мест.", "price": 22990.0, "tags": ["планшет", "samsung", "android", "мобильный"], "aliases": ["tablet", "таб", "самсунг планшет"], "attributes": {"brand": "Samsung", "screen": "10.5", "os": "Android"}},
    {"id": 157, "sku": "STE-0157", "title": "Планшет Apple iPad 10.9 Wi-Fi 64GB", "category": "планшеты", "description": "Планшет Apple для руководящего состава.", "price": 44990.0, "tags": ["планшет", "apple", "ipad", "премиум"], "aliases": ["айпад", "ipad", "apple планшет"], "attributes": {"brand": "Apple", "screen": "10.9", "storage": "64 GB"}},
    {"id": 158, "sku": "STE-0158", "title": "Графический планшет Wacom Intuos S", "category": "планшеты", "description": "Графический планшет для дизайнеров и проектировщиков.", "price": 7990.0, "tags": ["графический планшет", "wacom", "дизайн"], "aliases": ["рисовальный планшет", "планшет для рисования"], "attributes": {"brand": "Wacom"}},

    # --- Дополнительные расходники (id 159-170) ---
    {"id": 159, "sku": "STE-0159", "title": "Тонер-картридж Kyocera TK-1200", "category": "расходные материалы", "description": "Оригинальный тонер-картридж для МФУ Kyocera.", "price": 4990.0, "tags": ["картридж", "kyocera", "тонер"], "aliases": ["тонер kyocera"], "attributes": {"brand": "Kyocera", "yield": "3000 стр"}},
    {"id": 160, "sku": "STE-0160", "title": "Тонер-картридж Brother TN-2375", "category": "расходные материалы", "description": "Тонер-картридж для принтеров и МФУ Brother.", "price": 3490.0, "tags": ["картридж", "brother", "тонер"], "aliases": ["тонер brother"], "attributes": {"brand": "Brother", "yield": "2600 стр"}},
    {"id": 161, "sku": "STE-0161", "title": "Фотобумага А4 глянцевая 100 листов", "category": "расходные материалы", "description": "Глянцевая фотобумага для цветной печати.", "price": 690.0, "tags": ["фотобумага", "глянцевая", "а4", "печать"], "aliases": ["бумага для фото", "глянцевая бумага"], "attributes": {"format": "A4", "type": "глянцевая", "sheets": "100"}},
    {"id": 162, "sku": "STE-0162", "title": "Плёнка для ламинирования А4 100 мкм (100 шт)", "category": "расходные материалы", "description": "Плёнка для ламинатора формата A4.", "price": 490.0, "tags": ["ламинирование", "плёнка", "а4", "расходник"], "aliases": ["плёнка для ламинатора"], "attributes": {"format": "A4", "thickness": "100 мкм", "qty": "100"}},

    # --- Серверные стойки (id 163-170) ---
    {"id": 163, "sku": "STE-0163", "title": "Серверный шкаф 19 дюймов 22U", "category": "серверы", "description": "Напольный серверный шкаф для размещения оборудования.", "price": 24990.0, "tags": ["шкаф", "серверный", "19 дюймов", "22u"], "aliases": ["серверная стойка", "телеком шкаф", "rack"], "attributes": {"height": "22U", "width": "19 дюймов"}},
    {"id": 164, "sku": "STE-0164", "title": "Полка для серверного шкафа 19 дюймов", "category": "серверы", "description": "Стационарная полка для размещения оборудования в стойке.", "price": 1990.0, "tags": ["полка", "серверная", "стойка", "19 дюймов"], "aliases": ["полка для стойки", "rack shelf"], "attributes": {"width": "19 дюймов"}},
    {"id": 165, "sku": "STE-0165", "title": "Блок розеток для серверной стойки 8 розеток", "category": "серверы", "description": "PDU для серверного шкафа.", "price": 3990.0, "tags": ["pdu", "блок розеток", "серверная", "питание"], "aliases": ["pdu", "блок питания серверный"], "attributes": {"sockets": "8"}},

    # --- Доп. ноутбуки для разнообразия (id 166-170) ---
    {"id": 166, "sku": "STE-0166", "title": "Ноутбук Irbis NB HP1100", "category": "ноутбуки", "description": "Отечественный ноутбук для программы импортозамещения.", "price": 39990.0, "tags": ["ноутбук", "irbis", "импортозамещение", "отечественный"], "aliases": ["российский ноутбук", "ноут ирбис"], "attributes": {"brand": "Irbis", "cpu": "Intel Celeron", "ram": "8 GB"}},
    {"id": 167, "sku": "STE-0167", "title": "Ноутбук Aquarius CMP NS685", "category": "ноутбуки", "description": "Ноутбук Аквариус для государственных закупок.", "price": 62990.0, "tags": ["ноутбук", "aquarius", "импортозамещение", "государственный"], "aliases": ["ноут аквариус", "аквариус"], "attributes": {"brand": "Aquarius", "cpu": "Intel Core i5", "ram": "16 GB"}},

    # --- Смартфоны (id 168-170) ---
    {"id": 168, "sku": "STE-0168", "title": "Смартфон Samsung Galaxy A54", "category": "смартфоны", "description": "Корпоративный смартфон для выездных сотрудников.", "price": 32990.0, "tags": ["смартфон", "samsung", "android", "мобильный"], "aliases": ["телефон samsung", "мобильный телефон", "мобильник"], "attributes": {"brand": "Samsung", "screen": "6.4", "ram": "8 GB"}},
    {"id": 169, "sku": "STE-0169", "title": "Смартфон Xiaomi Redmi Note 13", "category": "смартфоны", "description": "Бюджетный смартфон для массовой закупки.", "price": 18990.0, "tags": ["смартфон", "xiaomi", "бюджет", "android"], "aliases": ["телефон xiaomi", "сяоми", "мобильник"], "attributes": {"brand": "Xiaomi", "screen": "6.67"}},
    {"id": 170, "sku": "STE-0170", "title": "Рация Baofeng UV-5R (пара)", "category": "смартфоны", "description": "Пара раций для охраны и технического персонала.", "price": 3990.0, "tags": ["рация", "baofeng", "связь", "охрана"], "aliases": ["радиостанция", "walkie-talkie"], "attributes": {"brand": "Baofeng", "qty": "2"}},
]

# Write catalog
output_path = Path(__file__).resolve().parent.parent / "data" / "catalog.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(PRODUCTS, f, ensure_ascii=False, indent=2)

print(f"Generated {len(PRODUCTS)} products -> {output_path}")
